# Generated by Django 4.1.5 on 2023-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("mobile", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
